// Sample dataset representing SageMaker Batch Transform Output
const SAMPLE_INFERENCE_DATA = [
  {
    "TransactionID": "3000001",
    "fraud_score": 0.9421,
    "TransactionAmt": 950.00,
    "hour_of_day": 3,
    "ProductCD": "W",
    "card4": "visa",
    "card6": "credit",
    "P_emaildomain": "gmail.com",
    "card1": 10055,
    "addr1": 315.0,
    "dist1": 120.0,
    "explanation": "High transaction amount ($950.00) initiated at 03:00 AM off-peak hours with sudden geographic variance (addr1: 315, dist: 120km). Combined with high card velocity anomaly, this represents a severe account takeover indicator."
  },
  {
    "TransactionID": "3000002",
    "fraud_score": 0.9850,
    "TransactionAmt": 1450.50,
    "hour_of_day": 2,
    "ProductCD": "C",
    "card4": "mastercard",
    "card6": "credit",
    "P_emaildomain": "protonmail.com",
    "card1": 15400,
    "addr1": 204.0,
    "dist1": 500.0,
    "explanation": "Extremely high fraud probability (98.5%). Rapid sequential purchase attempts of luxury digital goods using high-risk anonymous email domain (protonmail.com) and extreme physical distance delta."
  },
  {
    "TransactionID": "3000003",
    "fraud_score": 0.0210,
    "TransactionAmt": 45.00,
    "hour_of_day": 14,
    "ProductCD": "W",
    "card4": "visa",
    "card6": "debit",
    "P_emaildomain": "yahoo.com",
    "card1": 13800,
    "addr1": 299.0,
    "dist1": 5.0,
    "explanation": "Low risk. Routine grocery purchase during daytime hours consistent with 18-month historical card usage profile."
  },
  {
    "TransactionID": "3000004",
    "fraud_score": 0.1145,
    "TransactionAmt": 120.00,
    "hour_of_day": 18,
    "ProductCD": "W",
    "card4": "mastercard",
    "card6": "debit",
    "P_emaildomain": "gmail.com",
    "card1": 9500,
    "addr1": 126.0,
    "dist1": 10.0,
    "explanation": "Low risk. Standard e-commerce checkout with matching billing and shipping zip codes."
  },
  {
    "TransactionID": "3000005",
    "fraud_score": 0.3420,
    "TransactionAmt": 75.25,
    "hour_of_day": 9,
    "ProductCD": "H",
    "card4": "discover",
    "card6": "credit",
    "P_emaildomain": "hotmail.com",
    "card1": 8700,
    "addr1": 441.0,
    "dist1": 2.0,
    "explanation": "Low-to-moderate risk. Minor address distance delta but transaction velocity remains within benign baseline."
  },
  {
    "TransactionID": "3000006",
    "fraud_score": 0.8120,
    "TransactionAmt": 680.00,
    "hour_of_day": 23,
    "ProductCD": "R",
    "card4": "visa",
    "card6": "credit",
    "P_emaildomain": "anonymous-temp.org",
    "card1": 14220,
    "addr1": 180.0,
    "dist1": 310.0,
    "explanation": "Suspicious late-night electronics purchase with temporary disposable email domain and elevated billing mismatch."
  },
  {
    "TransactionID": "3000007",
    "fraud_score": 0.0450,
    "TransactionAmt": 18.50,
    "hour_of_day": 12,
    "ProductCD": "W",
    "card4": "visa",
    "card6": "debit",
    "P_emaildomain": "icloud.com",
    "card1": 11200,
    "addr1": 310.0,
    "dist1": 1.2,
    "explanation": "Normal convenience store point-of-sale tap."
  },
  {
    "TransactionID": "3000008",
    "fraud_score": 0.9150,
    "TransactionAmt": 1200.00,
    "hour_of_day": 4,
    "ProductCD": "C",
    "card4": "amex",
    "card6": "credit",
    "P_emaildomain": "mailinator.com",
    "card1": 17800,
    "addr1": 505.0,
    "dist1": 420.0,
    "explanation": "High fraud probability. Cross-border digital gift card purchase using burner email and unverified device fingerprint."
  },
  {
    "TransactionID": "3000009",
    "fraud_score": 0.0890,
    "TransactionAmt": 85.00,
    "hour_of_day": 16,
    "ProductCD": "W",
    "card4": "mastercard",
    "card6": "debit",
    "P_emaildomain": "gmail.com",
    "card1": 13400,
    "addr1": 299.0,
    "dist1": 4.5,
    "explanation": "Low risk regular dining expense."
  },
  {
    "TransactionID": "3000010",
    "fraud_score": 0.7450,
    "TransactionAmt": 499.99,
    "hour_of_day": 1,
    "ProductCD": "H",
    "card4": "visa",
    "card6": "credit",
    "P_emaildomain": "outlook.com",
    "card1": 9800,
    "addr1": 315.0,
    "dist1": 85.0,
    "explanation": "Elevated risk review. Unusually large transaction for this card profile at 1:00 AM."
  }
];
