resource "local_file" "env_file" {
  filename        = "${path.module}/../../.env"
  file_permission = "0600"
  content = join("\n", [
    "# Auto-generated by Terraform — do not edit manually",
    "# Re-run 'terraform apply' in infra/terraform/ to regenerate",
    "AWS_REGION=${data.aws_region.current.name}",
    "SAGEMAKER_ROLE_ARN=${module.iam.sagemaker_execution_role_arn}",
    "FRAUDGUARD_S3_BUCKET=${module.s3.bucket_id}",
    "FRAUDGUARD_DYNAMODB_TABLE=${module.dynamodb.table_name}",
    "FRAUDGUARD_MODEL_PACKAGE_GROUP=${module.sagemaker.model_package_group_name}",
    "LAMBDA_EXECUTION_ROLE_ARN=${module.iam.lambda_execution_role_arn}",
    "LAMBDA_FUNCTION_NAME=${module.lambda.function_name}",
    "REALTIME_LAMBDA_FUNCTION_NAME=${var.enable_realtime_endpoint ? module.realtime_lambda[0].function_name : ""}",
    "REALTIME_ENDPOINT_URL=${var.enable_realtime_endpoint ? module.realtime_lambda[0].function_url : ""}",
    "API_GATEWAY_URL=${var.enable_realtime_endpoint ? module.api_gateway[0].api_endpoint_url : ""}",
    "FRAUD_SCORE_THRESHOLD=${var.fraud_score_threshold}",
    "",
  ])
}
