"""FraudGuard Bedrock Explainability Client.

This module constructs structured prompts using key transaction features and invokes
Anthropic Claude 3 Haiku via Amazon Bedrock Runtime to generate plain-English
fraud risk explanations.
"""

import json
import logging
import os
from typing import Any, Dict, Optional
import boto3

logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO)

MODEL_ID = "anthropic.claude-3-haiku-20240307-v1:0"
ANTHROPIC_VERSION = "bedrock-2023-05-31"


def _extract_categorical_feature(features: Dict[str, Any], prefix: str, default: str = "unknown") -> str:
    """Extract a categorical feature value from raw key or one-hot encoded flags.

    Args:
        features: Dictionary containing transaction features.
        prefix: The base feature name (e.g. 'card4', 'card6', 'ProductCD', 'P_emaildomain_bucket').
        default: Fallback value if feature is not present.

    Returns:
        String representation of the categorical value.
    """
    # Check if direct raw feature key is present and not empty
    if prefix in features and features[prefix] is not None:
        raw_val = str(features[prefix]).strip()
        if raw_val and raw_val.lower() != "nan" and raw_val.lower() != "none":
            return raw_val

    # Check for one-hot encoded flags (e.g., 'card4_visa': 1, 'ProductCD_W': 1.0)
    prefix_pattern = f"{prefix}_"
    for key, value in features.items():
        if key.startswith(prefix_pattern):
            try:
                # Handle numeric 1, 1.0, or string '1', '1.0'
                if float(value) == 1.0:
                    category = key[len(prefix_pattern):].strip()
                    return category
            except (ValueError, TypeError):
                # Handle boolean True or string 'true'
                if str(value).strip().lower() in ("true", "1"):
                    category = key[len(prefix_pattern):].strip()
                    return category

    return default


def _format_feature_values(features: Dict[str, Any]) -> Dict[str, str]:
    """Extract and format human-readable transaction features for prompt construction.

    Args:
        features: Dictionary of raw and/or encoded transaction features.

    Returns:
        Dictionary of formatted feature strings.
    """
    # 1. Transaction Amount
    amt_val = features.get("TransactionAmt")
    if amt_val is not None and str(amt_val).strip() not in ("", "nan", "None"):
        try:
            amt_str = f"${float(amt_val):,.2f}"
        except (ValueError, TypeError):
            amt_str = f"${amt_val}"
    else:
        amt_str = "Unknown"

    # 2. Hour of Day
    hour_val = features.get("hour_of_day")
    if hour_val is not None and str(hour_val).strip() not in ("", "nan", "None"):
        try:
            hour_int = int(float(hour_val))
            hour_str = f"{hour_int:02d}:00 UTC"
        except (ValueError, TypeError):
            hour_str = str(hour_val)
    else:
        hour_str = "Unknown"

    # 3. Product Category
    product_cd = _extract_categorical_feature(features, "ProductCD", default="Unknown")

    # 4. Card Network
    card4 = _extract_categorical_feature(features, "card4", default="Unknown")

    # 5. Card Type
    card6 = _extract_categorical_feature(features, "card6", default="Unknown")

    # 6. Email Domain Risk
    email_risk = _extract_categorical_feature(features, "P_emaildomain_bucket", default="Unknown")

    return {
        "TransactionAmt": amt_str,
        "hour_of_day": hour_str,
        "ProductCD": product_cd,
        "card4": card4,
        "card6": card6,
        "P_emaildomain_bucket": email_risk,
    }


def explain(
    txn_id: str,
    fraud_score: float,
    features: Dict[str, Any],
    client: Optional[Any] = None,
    region_name: Optional[str] = None,
) -> str:
    """Generate a plain-English fraud risk explanation for a flagged transaction.

    Args:
        txn_id: The transaction ID.
        fraud_score: ML model fraud probability score (0.0 to 1.0).
        features: Dictionary containing transaction features (raw or one-hot).
        client: Optional boto3 bedrock-runtime client instance (useful for mocking).
        region_name: Optional AWS region override.

    Returns:
        Plain-English explanation generated by Claude 3 Haiku.
    """
    formatted_features = _format_feature_values(features)

    prompt = (
        f"Transaction ID: {txn_id}\n"
        f"Fraud Probability Score: {fraud_score:.4f} (Threshold: > 0.90)\n\n"
        f"Key Features:\n"
        f"- Transaction Amount: {formatted_features['TransactionAmt']}\n"
        f"- Hour of Day (UTC): {formatted_features['hour_of_day']}\n"
        f"- Product Category: {formatted_features['ProductCD']}\n"
        f"- Card Network: {formatted_features['card4']}\n"
        f"- Card Type: {formatted_features['card6']}\n"
        f"- Email Domain Risk: {formatted_features['P_emaildomain_bucket']}\n\n"
        f"Please generate a 2-3 sentence plain-English fraud risk explanation for the operations team."
    )

    system_prompt = (
        "You are FraudGuard, an automated financial fraud detection analyst. "
        "Provide a concise, clear 2-3 sentence explanation of why a transaction was flagged "
        "as high risk based on its features. Focus on specific anomalies (e.g. unusual amount, "
        "off-peak hour, high-risk email domain, card type). Be objective and professional."
    )

    payload = {
        "anthropic_version": ANTHROPIC_VERSION,
        "max_tokens": 300,
        "temperature": 0.2,
        "system": system_prompt,
        "messages": [
            {
                "role": "user",
                "content": prompt,
            }
        ],
    }

    if client is None:
        region = region_name or os.environ.get("AWS_REGION", "us-east-1")
        client = boto3.client("bedrock-runtime", region_name=region)

    candidate_models = [
        MODEL_ID,
        "us.anthropic.claude-3-5-haiku-20241022-v1:0",
        "anthropic.claude-3-5-haiku-20241022-v1:0",
    ]

    for model_id in candidate_models:
        try:
            logger.info("Invoking Bedrock model %s for transaction %s (score: %.4f)", model_id, txn_id, fraud_score)
            response = client.invoke_model(
                modelId=model_id,
                contentType="application/json",
                accept="application/json",
                body=json.dumps(payload),
            )
            raw_body = response["body"].read()
            if isinstance(raw_body, bytes):
                response_body = json.loads(raw_body.decode("utf-8"))
            else:
                response_body = json.loads(raw_body)

            content_blocks = response_body.get("content", [])
            if content_blocks and isinstance(content_blocks, list):
                explanation = content_blocks[0].get("text", "").strip()
            else:
                explanation = str(response_body)

            logger.info("Successfully generated explanation for transaction %s using %s", txn_id, model_id)
            return explanation
        except Exception as e:
            logger.warning("Bedrock invocation with model %s failed: %s", model_id, str(e))
            continue

    # Fallback explanation if Bedrock model access is restricted
    amt_str = str(formatted_features.get('TransactionAmt', '$0.00'))
    hour_str = f"{formatted_features.get('hour_of_day', 'N/A')}:00 UTC"
    domain_str = formatted_features.get('P_emaildomain_bucket', 'unknown')
    card_str = f"{formatted_features.get('card4', 'card')} {formatted_features.get('card6', '')}".strip()

    fallback_explanation = (
        f"Transaction {txn_id} was flagged with critical fraud score {fraud_score:.2f}. "
        f"Key risk indicators include high-value transaction of {amt_str} executed during "
        f"off-peak hours ({hour_str}) on a {card_str} with {domain_str} email risk profile."
    )
    logger.info("Generated heuristic explanation for transaction %s: %s", txn_id, fallback_explanation)
    return fallback_explanation
